### ISSUE TITLE
Integration with WIP app

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#1901]
See https://github.com/marketplace/wip

I've been using this app for my repos for a while. Actually we already have PRs in [WIP] textual status in title so I think it will be usefull to make it explicit.

I understand that the application is installed on the GitHub account and then configured for use in separate repositories. I have not been able to install this application here and I think only organization owner can do it.

ping @joemcbride

**Comment by Shane32** [comment]
We can add this GitHub Action script to do the same thing without using a third party:
```
name: Check if PR title contains WIP

on:
  pull_request:
    types: 
      - opened
      - edited

jobs:
  check-title:
    runs-on: ubuntu-latest

    steps:
      - name: Fail if name '${{ github.event.pull_request.title }}' contains 'WIP'
        if: ${{ contains(github.event.pull_request.title, 'wip') }}
        run: |
          echo Error! PR title contains WIP: ${{ github.event.pull_request.title }}
          exit 1
```
